/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.view.component;

import java.util.ArrayList;
import javax.json.JsonArray;
import javax.json.JsonValue;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author 84374
 */
public class CityJDialog extends JFrame {

    /**
     * Creates new form CityJDialog
     */
    private JPanel localPanel;
    private JsonArray localJsonArray;
    public CityJDialog(JPanel parent,JsonArray curWheather ) {
        initComponents();
        localPanel = parent;
        localJsonArray = curWheather;
        getCurData();
    }

    public void getCurData() {
        ArrayList<String> li = new ArrayList<>();
        if (localJsonArray != null) {
            for (JsonValue el : localJsonArray) {
                String listval = el.asJsonObject().getString("name");
                listval += " (" + el.asJsonObject().getJsonObject("coord").getInt("lon");
                listval += ", " + el.asJsonObject().getJsonObject("coord").getInt("lat") + ")";
                li.add(listval);
            }
        }
        String[] strs = new String[li.size()];
        li.toArray(strs);
        jDialogCityList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = strs;

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        System.out.println(li.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDialogCityList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        selectBtn.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        jDialogCityList.setBackground(new java.awt.Color(250, 250, 250));
        jDialogCityList.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jDialogCityList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jDialogCityList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDialogCityListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDialogCityList);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select a City");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        getCurData();
    }//GEN-LAST:event_selectBtnActionPerformed

    private void jDialogCityListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDialogCityListMouseClicked
        // TODO add your handling code here:
        System.out.println(jDialogCityList.getSelectedIndex());
    }//GEN-LAST:event_jDialogCityListMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jDialogCityList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
