/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view.component;

import SingletonClass.LstHoaDonDangPhaChe_singleton;
import SingletonClass.LstHoaDon_singleton;
import SingletonClass.NV_singleton;
import com.view.form_Template.Container;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Ban;
import model.HoaDon;
import model.NhanVien;
import service.BanService;
import service.HoaDonService;

/**
 *
 * @author 84374
 */
public class CreateBillPane extends javax.swing.JFrame {

    /**
     * Creates new form CreateBillPane
     */
    HoaDonService hoaDonService = new HoaDonService();
    BanService banService = new BanService();
    JTable localTblHoaDon = new JTable();
    JTable localTblHoaDonDangPhaChe = new JTable();
    ArrayList<HoaDon> localLstHoaDon = LstHoaDon_singleton.getInstance().lstHoaDon;

    public CreateBillPane(JTable tblHoaDon, JTable tblHoaDonDangPhaChe) {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        localTblHoaDon = tblHoaDon;
        localTblHoaDonDangPhaChe = tblHoaDonDangPhaChe;
        lblMaNV.setText(NV_singleton.getInstance().nv.getMa());
        lblTenNV.setText(NV_singleton.getInstance().nv.getTen());
        SimpleDateFormat formatterDate = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formatterTime = new SimpleDateFormat("HH:MM");
        java.util.Date date = new java.util.Date();
        lblDateNow.setText(formatterDate.format(date));
        lblTimeNow.setText(formatterTime.format(date));
    }

    public int validateTxt(String txt) {
        int max = banService.getMax();
        int stt = 0;
        try {
            int txtNum = Integer.valueOf(txtBan.getText());
            if (txtNum <= max&&txtNum>0) {
                stt= 1;
            } else {
                stt= 0;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return stt;
    }

    public void save() {
        if(validateTxt(txtBan.getText())==1){
              int idBan = Integer.valueOf(txtBan.getText());
        Ban ban = banService.getBanByID(idBan);
        NhanVien nv = NV_singleton.getInstance().nv;
        HoaDon hoaDon = new HoaDon(null, ban, null, nv, null, null, null, 0, 0, null, 1, null);
        HoaDon hoaDonAdded = hoaDonService.saveHoaDon(hoaDon);
        LstHoaDon_singleton.getInstance().lstHoaDon.add(hoaDonAdded);
        LstHoaDonDangPhaChe_singleton.getInstance().lstHoaDonDangPhaChe.add(hoaDonAdded);
        DefaultTableModel modelHoaDon = new DefaultTableModel();
        modelHoaDon = (DefaultTableModel) localTblHoaDon.getModel();
        DefaultTableModel modelHoaDonDangPhaChe = new DefaultTableModel();
        modelHoaDonDangPhaChe = (DefaultTableModel) localTblHoaDonDangPhaChe.getModel();
        String thanhToanStt;
        String phaCheStt;
        if (hoaDonAdded.getTinhTrangThanhToan() == 0) {
            thanhToanStt = "Chưa TT";
        } else {
            thanhToanStt = "Đã TT";
        }
        if (hoaDonAdded.getTrangThaiPhaChe() == 0) {
            phaCheStt = "Chưa pha";
        } else {
            phaCheStt = "Đã pha";
        }
        modelHoaDon.addRow(new Object[]{LstHoaDon_singleton.getInstance().lstHoaDon.size(), hoaDonAdded.getMa(), hoaDonAdded.getBan().getTen(), thanhToanStt, phaCheStt});
        modelHoaDonDangPhaChe.addRow(new Object[]{LstHoaDonDangPhaChe_singleton.getInstance().lstHoaDonDangPhaChe.size(), hoaDonAdded.getMa(), hoaDonAdded.getBan().getTen(), thanhToanStt, phaCheStt});
        this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null,"Bàn không tồn tại trong hệ thống !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblDateNow = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTimeNow = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("TẠO HÓA ĐƠN MỚI");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bàn");

        lblDateNow.setForeground(new java.awt.Color(0, 0, 0));
        lblDateNow.setText("#GetDateHere");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ngày");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Giờ vào");

        lblTimeNow.setForeground(new java.awt.Color(0, 0, 0));
        lblTimeNow.setText("#getTime");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Mã NV");

        lblMaNV.setForeground(new java.awt.Color(0, 0, 0));
        lblMaNV.setText("#MaNV");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tên NV");

        lblTenNV.setForeground(new java.awt.Color(0, 0, 0));
        lblTenNV.setText("#tenNV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBan)
                            .addComponent(lblTimeNow)
                            .addComponent(lblTenNV)
                            .addComponent(lblMaNV)
                            .addComponent(lblDateNow)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(22, 22, 22))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblMaNV))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTenNV))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDateNow))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTimeNow))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            save();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDateNow;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTimeNow;
    private javax.swing.JTextField txtBan;
    // End of variables declaration//GEN-END:variables
}
