/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.view.component;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.accessibility.AccessibleContext;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;
import model.News;
import model.TinTuc;

/**
 *
 * @author 84374
 */
public class NewsCell extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private String dir = null;
    private int index = 0;
    private String localTitle = null;
    private static byte[] localImg = new byte[5000];

    public NewsCell(TinTuc news) {
//        String path = "C:\\Users\\84374\\Documents\\NetBeansProjects\\CoffeeShop\\src\\main\\java\\com\\view\\icon\\coffe.png";
//        File file = new File(path);
//        String absolutePath = file.getAbsolutePath();
//        dir = absolutePath;
        localImg = news.getHinhAnh();
        initComponents();
        lblTittle.setText("<html><p style=\"width:170px\">" + news.getTieuDe() + "</p></html>");
        lblDes.setText("<html><p style=\"width:170px\">" + news.getMoTa() + "</p></html>");
        
    }

    public String getDir() {
        return dir;
    }

    public void setDir(String dir) {
        this.dir = dir;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public String getLocalTitle() {
        return localTitle;
    }

    public void setLocalTitle(String localTitle) {
        this.localTitle = localTitle;
    }

    public static byte[] getLocalImg() {
        return localImg;
    }

    public static void setLocalImg(byte[] localImg) {
        NewsCell.localImg = localImg;
    }

    public JLabel getLblDes() {
        return lblDes;
    }

    public void setLblDes(JLabel lblDes) {
        this.lblDes = lblDes;
    }

    public JLabel getLblIMGNews() {
        return lblIMGNews;
    }

    public void setLblIMGNews(JLabel lblIMGNews) {
        this.lblIMGNews = lblIMGNews;
    }

    public JLabel getLblTittle() {
        return lblTittle;
    }

    public void setLblTittle(JLabel lblTittle) {
        this.lblTittle = lblTittle;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

  

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDes = new javax.swing.JLabel();
        lblIMGNews = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        lblDes.setText("#NameOfProduct");
        lblDes.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ImageIcon oriImgIcon = new ImageIcon(localImg);
        Image image = oriImgIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(203, 115, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        ImageIcon imageIcon = new ImageIcon(newimg);
        lblIMGNews.setIcon(imageIcon);

        //ImageIcon imageIcon = new ImageIcon(img); // load the image to a imageIcon
        //Image image = imageIcon.getImage(); // transform it
        //Image newimg = image.getScaledInstance(79,120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        //imageIcon = new ImageIcon(newimg);
        //lblmgProduct.setIcon(imageIcon);

        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTittle.setText("#NameOfProduct");
        lblTittle.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIMGNews, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDes, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblDes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIMGNews, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblIMGNews;
    private javax.swing.JLabel lblTittle;
    // End of variables declaration//GEN-END:variables
}
