/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.view.component;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.DecimalFormat;
import javax.accessibility.AccessibleContext;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author 84374
 */
public class ProductCell extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private String dir = null;
    private int index = 0;
    private static byte[] localImg = new byte[5000];
    public ProductCell(byte[] img, String nameOfProduct, Double priceOfProduct, String des ) {
//        String path = "C:\\Users\\84374\\Documents\\NetBeansProjects\\CoffeeShop\\src\\main\\java\\com\\view\\icon\\coffe.png";
//        File file = new File(path);
//        String absolutePath = file.getAbsolutePath();
//        dir = absolutePath;
        DecimalFormat formatter = new DecimalFormat("###,###,###");
        localImg = img;
        initComponents();
        lblNameProduct.setText(nameOfProduct);
        lblPriceProduct.setText(formatter.format(priceOfProduct)+"VNĐ");
        lblDes.setText(des);
    }

    public String getDir() {
        return dir;
    }

    public void setDir(String dir) {
        this.dir = dir;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public JLabel getLblDes() {
        return lblDes;
    }

    public void setLblDes(JLabel lblDes) {
        this.lblDes = lblDes;
    }

    public JLabel getLblNameProduct() {
        return lblNameProduct;
    }

    public void setLblNameProduct(JLabel lblNameProduct) {
        this.lblNameProduct = lblNameProduct;
    }

    public JLabel getLblPriceProduct() {
        return lblPriceProduct;
    }

    public void setLblPriceProduct(JLabel lblPriceProduct) {
        this.lblPriceProduct = lblPriceProduct;
    }

    public JLabel getLblmgProduct() {
        return lblmgProduct;
    }

    public void setLblmgProduct(JLabel lblmgProduct) {
        this.lblmgProduct = lblmgProduct;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNameProduct = new javax.swing.JLabel();
        lblmgProduct = new javax.swing.JLabel();
        lblPriceProduct = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblNameProduct.setText("#NameOfProduct");

        ImageIcon oriImgIcon = new ImageIcon(localImg);
        Image image = oriImgIcon.getImage(); // transform it
        Image newimg = image.getScaledInstance(79, 120, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        ImageIcon imageIcon = new ImageIcon(newimg);
        lblmgProduct.setIcon(imageIcon);

        //ImageIcon imageIcon = new ImageIcon(img); // load the image to a imageIcon
        //Image image = imageIcon.getImage(); // transform it
        //Image newimg = image.getScaledInstance(79,120,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        //imageIcon = new ImageIcon(newimg);
        //lblmgProduct.setIcon(imageIcon);

        lblPriceProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPriceProduct.setText("#PriceOfProduct");

        lblDes.setBackground(new java.awt.Color(51, 51, 51));
        lblDes.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblDes.setText("#Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNameProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(lblPriceProduct)
                    .addComponent(lblDes)
                    .addComponent(lblmgProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmgProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblNameProduct)
                .addGap(12, 12, 12)
                .addComponent(lblPriceProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDes)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblNameProduct;
    private javax.swing.JLabel lblPriceProduct;
    private javax.swing.JLabel lblmgProduct;
    // End of variables declaration//GEN-END:variables
}
